apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-frontend
  labels:
    app: ecom-frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%               # Allows up to 25% more Pods than desired during the update
      maxUnavailable: 25%         # Allows 25% of the Pods to be unavailable during the update
  selector:
    matchLabels:
      app: ecom-frontend
  template:
    metadata:
      labels:
        app: ecom-frontend
    spec:
      restartPolicy: Always         # Ensures the containers always restart on failure
      terminationGracePeriodSeconds: 30  # Graceful shutdown period of 30 seconds
      containers:
      - name: ecom-frontend
        image: gcr.io/ecommerce-test-437909/ecom-app:0.0.4-GLOBAL-STABLE  # Replace with your image version
        imagePullPolicy: Always  # Ensures the image is always pulled
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-frontend-service
spec:
  selector:
    app: ecom-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
