apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecom-frontend
  name: ecom-frontend
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: ecom-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecom-frontend
    spec:
      containers:
      - image: gcr.io/ecommerce-test-437909/ecom-app:0.0.2-GLOBAL-STABLE #CHANGE
        imagePullPolicy: Always
        name: ecom-frontend
        # env:
        #   - name: CURRENCY_EXCHANGE_SERVICE_HOST
        #     value: http://currency-exchange
        
        #     valueFrom: 
        #       configMapKeyRef:
        #         key: CURRENCY_EXCHANGE_SERVICE_HOST
        #         name: currency-conversion-config-map
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: ecom-frontend
  name: ecom-frontend
  namespace: default
spec:
  ports:
  - port: 3000 #CHANGE
    protocol: TCP
    targetPort: 3000 #CHANGE
  selector:
    app: currency-conversion
  sessionAffinity: ClientIP
  type: LoadBalancer