apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-frontend
  labels:
    app: ecom-frontend
spec:
  replicas: 1  # Number of replicas for load balancing and redundancy
  selector:
    matchLabels:
      app: ecom-frontend
  template:
    metadata:
      labels:
        app: ecom-frontend
    spec:
      containers:
      - name: ecom-frontend
        image: gcr.io/ecommerce-test-437909/ecom-app:0.1.25-GLOBAL-STABLE  
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://ecom-backend:5000"  # Internal connection to backend

---
apiVersion: v1
kind: Service
metadata:
  name: ecom-frontend
  labels:
    app: ecom-frontend
spec:
  selector:
    app: ecom-frontend
  ports:
    - protocol: TCP
      port: 3000   # Port that the service will expose
      targetPort: 3000  # Port on the container
      nodePort: 30002  # NodePort for external access (optional)
  type: NodePort  # NodePort type service to expose the application externally
