version: '3.8'

services:
  backend:
    image: ecom-api
    env_file: ./backend/.env  # Ensure this has your MongoDB Atlas connection string
    ports:
      - "5000:5000"
    networks:
      - ecommerce-net
    restart: always  # Restart policy for backend service

  frontend:
    image: ecom-app
    ports:
      - "3000:3000"
    networks:
      - ecommerce-net
    depends_on:
      - backend  # Frontend depends on backend
    restart: always  # Restart policy for frontend service

networks:
  ecommerce-net:
    driver: bridge
