# ecom-backend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecom-backend
  name: ecom-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: ecom-backend
        image: gcr.io/ecommerce-test-437909/ecom-api:0.0.6-GLOBAL-STABLE
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI  # Example of setting environment variables
          value: "mongodb+srv://tanvirauti2620:tanvir1234@cluster0.epkgqyp.mongodb.net/ecommerce?retryWrites=true&w=majority"  # Replace with your actual MongoDB URI
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-backend
  labels:
    app: ecom-backend
spec:
  selector:
    app: ecom-backend
  ports:
    - protocol: TCP
      port: 5000   # Port inside the cluster
      targetPort: 5000   # Container port
      nodePort: 30001   # NodePort for external access
  type: NodePort
